[build]
  pre_cmd = [ "bunx @tailwindcss/cli -i ./frontend/input.css -o ./assets/tailwind.css", "sqlc generate", "make migrate", "templ generate --notify-proxy" ]
  cmd = "go build -o ./tmp/main ."
  exclude_dir = ["assets", "tmp", "testdata", "node_modules", "migrations"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go", "sql\\/.*\\.go"]
  include_ext = ["go", "sql", "templ"]
